aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that has edit rights on cronjobs within the project.
      change the project's membership.
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cronjob_admin
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
#  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - apps
  attributeRestrictions: null
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - autoscaling
  attributeRestrictions: null
  resources:
  - horizontalpodautoscalers
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - batch
  attributeRestrictions: null
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - policy
  attributeRestrictions: null
  resources:
  - poddisruptionbudgets
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - networking.k8s.io
  attributeRestrictions: null
  resources:
  - networkpolicies
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - authorization.k8s.io
  attributeRestrictions: null
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - rolebindings
  - roles
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - rolebindings
  - roles
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - localresourceaccessreviews
  - localsubjectaccessreviews
  - subjectrulesreviews
  verbs:
#  - create
- apiGroups:
  - ""
  - security.openshift.io
  attributeRestrictions: null
  resources:
  - podsecuritypolicyreviews
  - podsecuritypolicyselfsubjectreviews
  - podsecuritypolicysubjectreviews
  verbs:
#  - create
- apiGroups:
  - ""
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - rolebindingrestrictions
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - buildconfigs
  - buildconfigs/webhooks
  - builds
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - builds/log
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - buildconfigs/instantiate
  - buildconfigs/instantiatebinary
  - builds/clone
  verbs:
#  - create
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - builds/details
  verbs:
#  - update
- apiGroups:
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - jenkins
  verbs:
#  - admin
#  - edit
#  - view
- apiGroups:
  - ""
  - apps.openshift.io
  attributeRestrictions: null
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  verbs:
# - create
# - delete
# - deletecollection
# - get
# - list
# - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - apps.openshift.io
  attributeRestrictions: null
  resources:
  - deploymentconfigrollbacks
  - deploymentconfigs/instantiate
  - deploymentconfigs/rollback
  verbs:
#  - create
- apiGroups:
  - ""
  - apps.openshift.io
  attributeRestrictions: null
  resources:
  - deploymentconfigs/log
  - deploymentconfigs/status
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreamimages
  - imagestreammappings
  - imagestreams
  - imagestreams/secrets
  - imagestreamtags
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams/status
  verbs:
 # - get
 # - list
 # - watch
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams/layers
  verbs:
# - get
# - update
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreamimports
  verbs:
#  - create
- apiGroups:
  - ""
  - project.openshift.io
  attributeRestrictions: null
  resources:
  - projects
  verbs:
#  - delete
#  - get
#  - patch
#  - update
- apiGroups:
  - ""
  - quota.openshift.io
  attributeRestrictions: null
  resources:
  - appliedclusterresourcequotas
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes/custom-host
  verbs:
#  - create
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes/status
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes/status
  verbs:
#  - update
- apiGroups:
  - ""
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - processedtemplates
  - templateconfigs
  - templateinstances
  - templates
  verbs:
#  - create
#  - delete
#  - deletecollection
  - get
  - list
#  - patch
#  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  attributeRestrictions: null
  resources:
  - networkpolicies
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - buildlogs
  verbs:
#  - create
#  - delete
#  - deletecollection
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - resourcequotausages
  verbs:
#  - get
#  - list
#  - watch
- apiGroups:
  - ""
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - resourceaccessreviews
  - subjectaccessreviews
  verbs:
#  - create
